### ISSUE TITLE
Lizenz festlegen

### ISSUE THREAD

**Issue by niccokunzmann** [bioPunkKitchen/wartung#1]
Die Lizenz sollte CC-BY-SA sein.
Wir müssten die dann auf allen Seiten und in eine LICENSE-Datei schreiben.
Dazu müssen wir die Seiten anpassen.

**Comment by speexy** [comment]
@niccokunzmann meinst du für den content oder für den code? sind license dateien nicht eher sowas wie GNU public license?

**Comment by niccokunzmann** [comment]
Man kann alles unter jeder Lizenz machen. Bei der Webseite verschwimmt das ja. Man kann CC-BY-SA benutzen für alles.

**Comment by niccokunzmann** [comment]
Es gab ja auch die open documentation license von Wikipedia und die nutzen jetzt CC-BY-SA, glaube ich.
Folgendes hatte ich zur Wahl an Björn geschrieben: 

> > Welche Commences würdes du für das LOGO empfehlen?
> 
> Ich würde für alles CC-BY-SA verwenden.
Dann kann man das einfach zusammen kopieren.
Sich als das bioPunk.kitchen auszugeben sollte dann immernoch nicht erlaubt sein.
> 
> ND ist schlecht für die Verbesserung
NC ist schlecht, weil wir die anderen Startups auch mit einbeziehen wollen.
Die dürfen das ruhig verwenden und verbessern.
Bei nur CC-BY bin sind die Änderungen unklar lizensiert, ich will aber, dass die Verbesserungen für mich gut verwendbar sind, deswegen SA.

**Comment by speexy** [comment]
ah, ok. bei gatsby werd ich gefragt, welche lizenz ich verwenden will, das landet dann in package.json. ist das equivalent zur licence-datei? oder ergänzend? 
ich denke für content sollten wir die lizenz in den footer und ins impressum schreiben. Können gern CC-BY-SA nehmen.

**Comment by niccokunzmann** [comment]
Ich weiß nicht, was in der package.json drin steht. Sicher können wir
das noch ändern.
Ich denke, es ist ergänzend, da die meisten Lizenzen nicht im Klartext
mitgeliefert werden und die package.json-Datei auch zum verpacken und
verteilen von Paketen dient, die
nur eine kleine Lizenzanmerkung auf ihrer Webseite haben, sowas wie MIT,
oder GPL.
Es dient eher der Information und dem Überblick in der
package.json-Datei. - Meine Meinung.
