### ISSUE TITLE
Choose framework/stack

### ISSUE THREAD

**Issue by speexy** [bioPunkKitchen/wartung#4]
what do we want the site to build with?
discuss trade off between dev speed and github build convenience and extensibility

**Comment by speexy** [comment]
I started to hate jekyll because there is no good representation of state in the frontend. I'm working with Gatsby JS now which I think is a good compromise. Start of with a static page and hook in dynamic bits if needed at some other point. potentially reuse components should we move away from static in general

**Comment by niccokunzmann** [comment]
My concerns are:
1. it should be easy to identify where to edit the site, possibly add an edit pencil to most of the text pages
2. it should allow for an beginner-friendly format for text which is markdown, not HTML

I had a quick look at gatsby, so I would say, it supports markdown (2). What do you think about (1)?

**Comment by niccokunzmann** [comment]
I can also create an automated build process which pushes the page to the branch.

**Comment by speexy** [comment]
about 1, you mean here on github or on the actual page? who should edit?
I use gatsby with netlify cms which can do a login via github. and changes are tracked in git/github

**Comment by niccokunzmann** [comment]
Cool. I do not know anything about this. Anyone with a github account should be able to edit the site.

**Comment by niccokunzmann** [comment]
That is great: https://www.gatsbyjs.org/docs/adding-markdown-pages/#adding-markdown-pages it should be possible to also use markdown.

**Comment by niccokunzmann** [comment]
Let's use Gatsby, then. I do not know how to start at the moment. I can try but you can do it, too, if you like. What do you think?

**Comment by speexy** [comment]
I have a default gatsby repo, and I was going to make the page anyway. however, I am super busy right now, and can't work on in the short term. but yes, happy to set up a gatsby page.
@bthuw and I talked a bit about the structure of the page. But nothing final. I think it would be good to have another desing iteration and decide on some sort of first version that we'd like to go live.
and with netlify you even have a richtext editor :)

**Comment by niccokunzmann** [comment]
This sounds awesome. I will just add content to the jekyll page, and do
no programming.
It should be easy to merge these versions together as only the text of
mine is important.
This can be done, when there is time. No haste :)

**Comment by niccokunzmann** [comment]
I pushed a Gatsby version to the [Gatsby branch](https://github.com/bioPunkKitchen/bioPunkKitchen.github.io/tree/gatsby)

**Comment by niccokunzmann** [comment]
It is now published to the master branch. I guess it is "chosen". If you like, you can still comment.
